version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5436:5432"  # Изменено с 6543 на 5436
    volumes:
      - ./volumes/postgres/stats_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  comment-db:
    image: postgres:16.1
    container_name: comment-db
    ports:
      - "5435:5432"  # Изменено с 6542 на 5435
    environment:
      - POSTGRES_DB=comment_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    volumes:
      - ./volumes/postgres/comment_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "5433:5432"  # Изменено с 6541 на 5433
    environment:
      - POSTGRES_DB=event_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    volumes:
      - ./volumes/postgres/event_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "5434:5432"  # Изменено с 6540 на 5434
    environment:
      - POSTGRES_DB=request_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    volumes:
      - ./volumes/postgres/request_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "5432:5432"  # Изменено с 6539 на 5432
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    volumes:
      - ./volumes/postgres/user_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10