spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6538/analyzer-db
    username: adb
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:
        action: analyzer.actions
        similarity: analyzer.similaritys

hibernate:
  jdbc:
    time_zone: UTC

logbook:
  format:
    style: http

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE

user-action:
  view: 0.4
  register: 0.8
  like: 1.0

kafka:
  topics:
    action: stats.user-actions.v1
    similarity: stats.events-similarity.v1