# БЕЗ server.port и eureka!
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm
    username: ewm
    password: ewm
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

stats:
  server:
    url: http://stats-server

logging:
  level:
    ru.practicum: DEBUG
    org.hibernate.SQL: DEBUG