server:
  port: 0  # Динамический порт

spring:
  application:
    name: stats-server

  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  # Hibernate создаст таблицы автоматически
  jpa:
    hibernate:
      ddl-auto: update  # или create для первого запуска
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/stats
    username: test
    password: test
    hikari:
      maximum-pool-size: 10

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  jackson:
    time-zone: Europe/Moscow

logging:
  pattern:
    console: "[%X{requestId}] %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  level:
    ru.practicum: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
    preferIpAddress: false